spring:
  application:
    name: config-default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-witch-eureka: tue
    service-url:
      defaultZone: http://localhost:8761/eureka
