server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gusmunoz1221/-microservices-infrastructure
          clone-on-start: true